# Generated by Django 3.1.4 on 2020-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201224_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%y%m%d/', verbose_name='Фотография'),
        ),
    ]
